### ISSUE TITLE
No blocks visible in the Visual Editor

### ISSUE THREAD

**Issue by kristiank** [GIRA/UziScript#2]
I recently updated from v0.1.1 to v0.2.1, but it hasn't changed a behaviour that started with the first version. Namely, I don't see the blocks palette in the visual editor. Comparing to the [screenshot here](https://raw.githubusercontent.com/GIRA/UziScript/master/docs/img/uzi_visualeditor.png), I can't see the gray panel in the middle (with Tasks, GPIO, Motors, etc). I am using Firefox 60.9.0esr on Debian.

I do see all the rest of the GUI and I am able to load an .uziblock file that I have made earlier and make changes to it. If I press the Verify button I get an error message "MessageNotUnderstood: UndefinedObject>>do:". If I look at the web browser console and refresh the page, I get the message
```JSON
{…}​abort: function abort()​always: function always()​complete: function add()​done: function add()​error: function add()​fail: function add()​getAllResponseHeaders: function getAllResponseHeaders()​getResponseHeader: function getResponseHeader()​overrideMimeType: function overrideMimeType()​pipe: function then()​priority: 0​progress: function add()​promise: function promise()​readyState: 4​responseText: "MessageNotUnderstood: UndefinedObject>>do:"​setRequestHeader: function setRequestHeader()​state: function state()​status: 400​statusCode: function statusCode()​statusText: "Bad Request"​success: function add()​then: function then()​__proto__: Object { … } uzi.js:73:3
```

This panel simply just disappeared at one moment and I can't get it back. I have tried to inspect the source code to find if some div is simply hidden, but with no results. I can't find any problems (the network pane shows that all elements are loaded and the communication between Arduino and the computer seems work). Also I am able to set and get data from the Arduino via Squeak and also via the Uzi Text Editor. Do I need to remove the script that I put running with the Text editor before being able to use the Visual editor?

The Monitor page doesn't show any data from the Arduino. But all pages seem to "function" and they are connected to the Arduino.

Any ideas from which angle I could start debugging this behaviour? Thank you!

**Comment by RichoM** [comment]
Hi Kristian,

I couldn't reproduce the issue yet, maybe the data in your browser's localstorage is too old and incompatible with the new version. Could you try removing it and see if it fixes the problem? Here is a screenshot with all the localstorage keys that should be removed: 

![localstorage](https://user-images.githubusercontent.com/1226503/68237226-7fe7c480-ffe5-11e9-9875-be19112d8a5c.png)

Please note, however, that since the v0.2 release all the demos have been replaced with the Physical Bits IDE prototype. It should look like this: 

![ide](https://user-images.githubusercontent.com/1226503/68237266-93932b00-ffe5-11e9-89f3-48d5058d9c42.png)

I haven't remove the code for the old demos yet because I still haven't finished porting the monitoring and debugger into the IDE. I should update the documentation and release notes soon, though.

**Comment by kristiank** [comment]
Great! I'll try it on the way home from work.

**Comment by kristiank** [comment]
I can't find any information on the internet about this Physical BITS thing, it sounds very interesting!

**Comment by RichoM** [comment]
Thanks! Physical BITS is the IDE we are trying to build, while UziScript is the underlying language.

**Comment by kristiank** [comment]
> Physical BITS is the IDE we are trying to build
You are so awsome!

The IDE now works (don't ask me why) but I haven't had time to try it out really. But I can verify everything works fine communicating with a TotemDUINO using UziScript from Squeak (e.g. using potentiometers to steer a car on the screen).
